apiVersion: v1
kind: Service
metadata:
  name: llmcore
  namespace: ns-llm
spec:
  type: ClusterIP
  selector:
    app: llmcore
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: grpc
---
# NodePort для доступа к HTTP API извне кластера
apiVersion: v1
kind: Service
metadata:
  name: llmcore-external
  namespace: ns-llm
spec:
  type: NodePort
  selector:
    app: llmcore
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
