apiVersion: v1
kind: Service
metadata:
  name: llmdb
  namespace: ns-llm
spec:
  type: ClusterIP
  selector:
    app: llmdb
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
---
# NodePort для доступа извне кластера
apiVersion: v1
kind: Service
metadata:
  name: llmdb-external
  namespace: ns-llm
spec:
  type: NodePort
  selector:
    app: llmdb
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30435
    protocol: TCP
    name: postgres
