apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llmdb-data
  namespace: ns-llm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Используйте storageClassName при необходимости
  # storageClassName: local-path
